### ISSUE TITLE
Wrong prediction when question downvoted to +1 by the user running the Roomba Forecaster

### ISSUE THREAD

**Issue by techraf** [makyen/StackExchange-userscripts#26]
State:

- Question **closed**
- Question **+1** resulting from +2 -1 (from the user running the Roomba Forecaster)
- Answer **+1**

Prediction: **Roomba: No, down-vote answer will roomba**

----

There is a brief flash of "downvote both question and answer", then the script "realises" question was already downvoted by the user and replaces the prediction with "down-vote answer will roomba" - this is wrong and should be an unconditional "No".

(after downvoting the answer, the prediction changes to "No")

**Comment by makyen** [comment]
Thanks for reporting this. It will be fixed in the next version.

The "flash", a brief interval between when the Roomba information is first placed in the page and when it's updated to reflect the current vote status, is because the Roomba information is placed in the page once the HTML is available. At that point, if the user has voted on the question isn't available on the page. The user's votes are added by SE after an AJAX call to fetch the information. That AJAX call is performed after all the SE scripts in the page are ready. This is a user noticeable period of time, which may be quite long in some circumstances.

There are at least 3 solutions to the "flash":
1. Wait to put the Roomba information in the page until the data is available. Given that the difference in time can be many seconds, depending on the browser and SE, I'd rather have the Roomba information as soon as possible and update it when the voting information becomes available.
2. Request the information from the SE API. This would require a user-auth token and result in consuming SE API requests, which the script currently doesn't do, unless the user has set an option to do so. Note: it will use the SE API to get data in the close-vote review queue (new functionality), because all the data needed isn't in the page.
3. The votes could be fetched from the same realtime URL which SE fetches them. However, there are significant rate limits on this URL, which may result, in some instances, in the user being rate-limited from using SE at all. Thus, I'm not a fan of this solution.
