### ISSUE TITLE
Roomba Forecaster tooltip explanation has insufficient inline width

### ISSUE THREAD

**Issue by Tyler-H** [makyen/StackExchange-userscripts#42]
I am seeing the `<div id="roombaTableDivDiv">` wrapper of the explanation (the div you see on hover) have insufficient width declared explicitly inline:

![image](https://user-images.githubusercontent.com/206492/122820032-2959f780-d2a9-11eb-933d-c1d0e7e44023.png)

If I enable hover styles and toggle hover, I see there's a `#roombaTableDivDiv` inline style of `width:292px;` applied. If I disable that style in my browser inspector, the div shown on hover is the correct, full width again.

Version 2.2.5 of Roomba Forecaster

The question I'm seeing this on is here: https://stackoverflow.com/questions/24282636/how-to-handle-flow-of-different-events-in-nested-buttons-of-jquery-mobile-listvi

**Comment by makyen** [comment]
Thanks for the report.

Ironically, I, also, noticed this a few days ago (3) and fixed it in my local copy. Limiting the width of the div is a hold-over from when the question status/data used to be in the sidebar. The fix was to change the selector to `#sidebar #roombaTableDivDiv`. That should still allow for it to work the same for those who use the userscript which puts the status information back into the sidebar.
